[package]
name = "tri_area"
version = "0.1.0"
edition = "2021"

[workspace]
members = {
    tri_area
}
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
